services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nlsbard
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_dump:/db_dump
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://mike:${POSTGRES_PASSWORD}@db/nlsbard
      NLS_BARD_USERNAME: ${NLS_BARD_USERNAME}
      NLS_BARD_PASSWORD: ${NLS_BARD_PASSWORD}
    volumes:
      - .:/app
      - ${WIN_DOWNLOADS_PATH}:/home/chrome/Downloads  # Updated this line
    ports:
      - "3000:3000"
    command: tail -f /dev/null  # This will keep the container running after app ends

volumes:
  postgres_data:
    name: nls_bard_postgres_data
    external: true
