version: '3.8'

x-comment: |
  This is the docker-compose file for PRODUCTION.
  It is optimized for stability, security, and performance:
  - It builds a self-contained image using Dockerfile.prod.
  - The application code is part of the image, not mounted from the host.
  - It runs the application automatically using the Dockerfile's ENTRYPOINT.
  - It includes restart policies to ensure services recover from failures.

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: mike
      POSTGRES_DB: nlsbard
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://mike:${POSTGRES_PASSWORD}@db/nlsbard
      # Pass individual DB components for the Sequel connection helper
      POSTGRES_HOST: db
      POSTGRES_DB: nlsbard
      POSTGRES_USER: mike
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NLS_BARD_USERNAME: ${NLS_BARD_USERNAME}
      NLS_BARD_PASSWORD: ${NLS_BARD_PASSWORD}
    volumes:
      # Use a named volume for downloads. The path inside the container
      # matches the home directory of the 'appuser' created in Dockerfile.prod.
      - downloads:/home/appuser/Downloads
    restart: unless-stopped

volumes:
  postgres_data:
  downloads: