name: 'nls-bard-prod' # Unique name for the production environment

x-comment: |
  This is the docker-compose file for PRODUCTION.
  It is optimized for stability, security, and performance:
  - It builds a self-contained image using Dockerfile.prod.
  - The application code is part of the image, not mounted from the host.
  - It runs the application automatically using the Dockerfile's ENTRYPOINT.
  - It includes restart policies to ensure services recover from failures.

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: mike
      POSTGRES_DB: nlsbard
    volumes:
      - /home/mike/postgres-data-prod:/var/lib/postgresql/data  # Separate prod database volume
      - ./db_init:/docker-entrypoint-initdb.d  # Auto-run SQL scripts on empty database
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://mike:${POSTGRES_PASSWORD}@db/nlsbard
      # Pass individual DB components for the Sequel connection helper
      POSTGRES_HOST: db
      POSTGRES_DB: nlsbard
      POSTGRES_USER: mike
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NLS_BARD_USERNAME: ${NLS_BARD_USERNAME}
      NLS_BARD_PASSWORD: ${NLS_BARD_PASSWORD}
      CONTAINER_DOWNLOAD_PATH: /home/appuser/Downloads
    volumes:
      # Mount the host's download path into the container for consistency with dev.
      - ${WIN_DOWNLOADS_PATH}:/home/appuser/Downloads
    restart: unless-stopped
