version: '3.8'
name: 'nls-bard-dev-container' # Unique project name for the dev container environment

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${HOST_UID:-1000}
        - GID=${HOST_GID:-1001}
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
 
